runtime: python310

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /favicon.png
  static_files: public/favicon.png
  upload: public/favicon.png
  secure: always

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  secure: always

entrypoint: gunicorn -c gunicorn.py -b :$PORT main:app
