runtime: python312

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*\.(svg|png|txt))$
  static_files: public/\1
  upload: public/.*\.(svg|png|txt)$

- url: /favicon.ico
  static_files: public/favicon.png
  upload: public/favicon.png

entrypoint: gunicorn -c gunicorn.py -b :$PORT main:app

###################################################

automatic_scaling:
  max_instances: 1
